//Created 19/02/2020

#ifndef __FEFEASwitch__h
#define __FEFEASwitch__h

#include <vector>
#include "comm/Connection.hpp"
#include "comm/DataPackage.hpp"
#include "common/Config.hpp"
#include "common/Fifo.hpp"
#include "common/Stats.hpp"
#include "common/Unit.hpp"
#include "common/types.hpp"

/*
*/

class FEASwitch : public Unit {
 private:
  std::size_t m_level;            // Level where the Adder is set in the tree
  std::size_t m_numInLevel;       // Number of the Adder in the level
  std::size_t m_numMs;            // These three parameters are for routing. In hardware it is not neccesary since it is used a bit vector
  std::size_t m_inputPorts;       // Input port per branch (left, right).
  std::size_t m_outputPorts;      // output port
  std::size_t m_forwardingPorts;  //Intermedium links between some nodes of the same level
  std::size_t m_buffersCapacity;  //Buffers size in bytes
  std::size_t m_portWidth;        //Bit width of each port

  std::size_t m_busId;    //CollectionBus connected to this ASwitch
  std::size_t m_inputId;  //Number of input of the Collection Bus busID connected to this AS.

  //Inputs fifos. These Fifos are not in the picture of figure 3. However, we build it for simplicity and extensibility
  Fifo* p_inputPsumLeftFifo;   // Array of packages that are received
  Fifo* p_inputPsumRightFifo;  // Array of packages that are received
  Fifo* p_inputFwFifo;         // Array of packages that are received though the fw link
  Fifo* p_inputFwBelowNodesFifo;

  // Output Fifos
  Fifo* p_outputPsumFifo;  // Output fifo to the parent
  Fifo* p_outputFwFifo;    // Ouptut fifo to the fw link

  std::vector<DataPackage*> m_psumsCreated;  // Array of packages generated by this specific AS. Used to delete the packages at the end of exec

  std::size_t m_currentCapacity;                         // the capacity must not exceed the input bw of the connection
  Connection* p_inputLeftConnection;                     // This is the input left connection of the Adder
  Connection* p_inputRightConnection;                    // This is the input right connection of the adder
  Connection* p_outputConnection;                        // This is the output connection of the adder
  Connection* p_memoryConnection;                        // This is the connection of the adder with the memory collect bus to write the psum if neccesary
  std::vector<Connection*> m_inputConnectionsToForward;  //Array of connections to get data to be forwarded every moment.
  Connection* p_upNodeForwardingConnection;              //Connection to forward the psum to the adder that sums
  // Related intermedimum links (forwardings). This links are NULL if the Adder has no connection with neighbour. (Look up the paper of MAERI for more details)
  Connection*
      p_forwardingConnection;  // connection from the neighbour Adder. In hardware we use two. One for inputs and another for outputs and the adder slect the correct one
  // using the configuration. However, in software is enough with one link and a flag that indicates if it is going to receive or send data

  cycles_t m_latency;  // Number of cycles to compute a sum. This is configurable since can vary depending on the implementation technology and frequency

  //Configuration signals. Note the direction of the fl is also a configuration signal.
  fl_t m_flDirection;                // RECEIVE or SEND. Each adder will be configured differently
  bool m_fwEnabled;                  //Set if the fw is enabled
  adderconfig_t m_configMode;        // Configuration mode of the adder. ADD_2_1, ADD_3_1, ADD_1_1_PLUS_FW_1_1 or  FW_2_2
  adderoperation_t m_operationMode;  // Operation to perform by the AS (ADDER, COMPARATOR). DEFAULT=ADDER
  bool m_leftChildEnabled;           // Indicates if the as receives data from the left child
  bool m_rightChildEnabled;          // Indicates if the as receives data from the right child
  bool m_forwardToMemory;            // To optimize. If the psum is already completed send directly to the collection bus
  bool m_forwardToFoldNode;

  //Operation functions. This functions can be changed in order to perform different types of length operations
  DataPackage* perform_operation_2_operands(DataPackage* pck_left, DataPackage* pck_right);                            //Perform 2:1 sum
  DataPackage* perform_operation_3_operands(DataPackage* pck_left, DataPackage* pck_right, DataPackage* pck_forward);  //Perform 3:1 sum
  //Routing functions. Based on the configuration of the switch, the routing is done in a different way.
  void route_2_1_config();              //2:1 routing. This perform a sum with left and right inputs and send the output to the parent link or fw link.
  void route_3_1_config();              //3;2 routing. This perform a 3:1 sum with left, right and fw link inputs and send the output to the parent
  void route_1_1_plus_fw_1_1_config();  //1:1 ADD plus 1:1 fw. Send one branch to the parent and the other to the fw link
  void route_fw_2_2_config();           //2:2 fw. This perform a forwarding of the 2 left and right inputs sending it through the parent link.
  void route_fold_config();

  cycles_t local_cycle;
  ASwitchStats aswitchStats;  //To track the behaviour of the FEASwitch

  //Extensions
  DataPackage* p_temporalRegister;  //Temporal register to accumulate partial sums
  std::size_t m_nPsums;             //Number of psums before accumulation
  std::size_t m_currentPsum;        //Current psum performed

 public:
  FEASwitch(stonne_id_t id, std::string name, std::size_t level, std::size_t num_in_level, Config stonne_cfg);
  FEASwitch(stonne_id_t id, std::string name, std::size_t level, std::size_t num_in_level, Config stonne_cfg, Connection* inputLeftConnection,
            Connection* inputRightConnection, Connection* forwardingConnection, Connection* outputConnection, Connection* memoryConnection);
  ~FEASwitch();

  //Connection setters
  void setInputLeftConnection(Connection* inputLeftConnection);                                    // Set the input left connection of the Adder
  void setInputRightConnection(Connection* inputRightConnection);                                  // Set the input right connection of the Adder
  void setOutputConnection(Connection* outputConnection);                                          // Set the output connection of the Adder
  void setForwardingConnection(Connection* forwardingConnection);                                  // Set the forwarding connection of the Adder
  void setMemoryConnection(Connection* memoryConnection, std::size_t busID, std::size_t inputID);  // Set the memory connection of the adder
  void setUpNodeForwardingConnection(Connection* upNodeForwardingConnection);                      // Set the connection to the up node that manages the folding
  void addInputConnectionToForward(Connection* inputConnectionToForward);

  void setNPSums(std::size_t n_psums) { this->m_nPsums = n_psums; }

  // Getters
  std::size_t getLevel() const { return this->m_level; }

  std::size_t getNumInLevel() const { return this->m_numInLevel; }

  std::size_t getInputPorts() const { return this->m_inputPorts; }  // Get the input bw per branch

  std::size_t getOutputPorts() const { return this->m_outputPorts; }  // Get the output ports

  std::size_t getForwardingPorts() const { return this->m_forwardingPorts; }  // Get the forwarding ports

  cycles_t getLatency() const { return this->m_latency; }  // Get the number of cycles to compute

  fl_t getFlDirection() const { return this->m_flDirection; }  // Get the direction of the fl for the current configuration. RECEIVE or SEND

  bool isFwEnabled() const { return this->m_fwEnabled; }

  adderconfig_t getConfig() const {
    return this->m_configMode;
  }  // Get the current configuration of the adder. ADD_2_1, ADD_3_1, ADD_1_1_PLUS_FW_1_1 or  FW_2_2

  adderoperation_t getOperationMode() const { return this->m_operationMode; }  // Get the current operation configured (ADD or POOL) TODO POOL NOT SUPPORTED YET

  //Configuration settings (control signals)
  void setForwardingLinkDirection(fl_t fl_direction);    // Set if the configuration of the FL for a certain AS is RECEIVE or SEND. This is a control signal
  void setConfigurationMode(adderconfig_t config_mode);  // Set the configuration mode of the adder. This depends on the compiler and it is a control signal.
  void setChildsEnabled(bool left_child_enabled, bool right_child_enabled);  //Indicates if the as receives data from left and right
  void setForwardingToMemoryEnabled(bool forwarding_to_memory);
  void setForwardingToFoldNodeEnabled(bool forwarding_to_fold_node);
  void setOperationMode(adderoperation_t operation_mode);

  // Functionality
  void send();            //Packages of data to be sent depending on routing.
  void receive_childs();  //take data from inputLeftConnection and inputRightConnection and save it in its corresponding buffers
  void receive_fwlink();
  void receive_below_nodes_fwlinks();

  //Buffers seem not to appear in the Adder switch implemented in hardware (just there is a buffer in the output). However, they are just a logical unit used in the software model.
  //This is done like this to make easier possible future implementations.

  void cycle();  //Computing a cycle. Based on routing the AS decides where the data goes.

  void printConfiguration(std::ofstream& out,
                          std::size_t indent);  //This function prints the configuration of FEASwitch such as  the operation mode, augmented link enabled, etc
  void printStats(std::ofstream& out, std::size_t indent);
  void printEnergy(std::ofstream& out, std::size_t indent);
};

#endif
